{
 "title": "SRE Webinar App",
 "tags": [
  "flask",
  "react",
  "python",
  "frontend",
  "backend"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ruby_http_duration_seconds_sum", "legendFormat": "{{controller}}" }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "graph",
   "description": "Successful calls to our API backend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ruby_http_requests_total{status=~\"2..\"}[1m]",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx's",
   "type": "graph",
   "description": "Graph of calls that are totally failing, grouped by backend controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ruby_http_requests_total{status=~\"5..\"}[1m]",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}